comments in english
hyansuper/rcute-cozmars pull request #21
Opened 2021-01-21 16:42 UTC by anjok

2021-01-21 16:45 UTC, anjok commented
Note: I did nothing more than a bunch of pasting into translate.google.com, copying out and pasting it into the python files. Then I installed the requirements and ran "python3 -m rcute_cozmars" and fixed things until it ran. I didn't read the translations in detail, but they look ok to me. At least they make more sense than Chinese characters :)

2021-01-21 19:05 UTC, anjok commented
I also have a version of the docs in English as a PDF, you can paste the URL into translate.google.com like this:

https://translate.google.com/translate?hl=&sl=zh-CN&tl=en&u=https%3A%2F%2Frcute-cozmars.readthedocs.io%2F_%2Fdownloads%2Fzh_CN%2Flatest%2Fpdf%2F

and get it in one book. Looks neat :)

2021-01-21 19:06 UTC, anjok commented
You might want to write that into your README.md

2021-01-22 12:11 UTC, hyansuper requested changes

2021-01-22 12:11 UTC, hyansuper commented on rcute_cozmars/button.py
> -from . import util
Don't change any code，they are tested

2021-01-22 12:11 UTC, hyansuper commented on rcute_cozmars/button.py
> +    """ Button
Do you think it is better without doc string in cases where function names or class names are straight forward？it looks silly to put the same word under def.

2021-01-23 08:32 UTC, anjok commented
I force push a commit with the code changes removed, but it would have been ok anyway as python doesn't need the missing spaces. That was the way that translate.google.com returned the text.

As for the "Foo" comments... what I *normally* do at work is not write any docs, expect when it's not totally apparent from the names what the respective thing does. And then mostly abstracts at the class level.

But then again: I'm a pretty experienced developer and work with people like myself. So your target audience may be different. 

If you want more, you can take a look at the Cozmo SDK and see if that provides you with more info than what you would have intuited in the first place.

2021-01-23 09:27 UTC, merged